### ISSUE TITLE
Gemfile missing

### ISSUE THREAD

**Issue by dirkolbrich** [FreeCAD/DevelopersHandbook#18]
I can not install the ruby bundles without the missing Gemfile. With only the present Gemfile.lock, `bundle install` will return an error.
System macOS M1, freshly cloned repo with `git clone https://github.com/FreeCAD/DevelopersHandbook.git freecad-DevelopersHandbook`.

```
freecad-DevelopersHandbook git:(master) ✗ uname -m
arm64
➜  freecad-DevelopersHandbook git:(master) ✗ ruby -v
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]
➜  freecad-DevelopersHandbook git:(master) ✗ bundle -v
Bundler version 2.3.26
➜  freecad-DevelopersHandbook git:(master) ✗ bundle install
Could not locate Gemfile
```

**Comment by dirkolbrich** [comment]
Nevermind. Found some articles in the net, which describe to add a local `Gemfile` with some basic setup -> see https://github.com/github/pages-gem

**Comment by sliptonic** [comment]
Would it hurt to add the Gemfile to the repo?
I haven't been able to get local build to work yet

**Comment by dirkolbrich** [comment]
Probably not, but I don't know how the Github build pipeline reacts to a Gemfile. The content ist pretty simple:
```txt
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem "webrick", "~> 1.8"
```
