### ISSUE TITLE
Contributors talk about things they don't know

### ISSUE THREAD

**Issue by Zolko-123** [FreeCAD/DevelopersHandbook#47]
I've discovered recently this developers handbook, by accident, and I have been quite surprised how much the "assembly" question is emphasized. Looking at the developers involved in this handbook, I can't fail to notice that NONE of the contributors has EVER talked and participated in the FreeCAD assembly forums. I also have NEVER EVER seen any assembly model made by any of these contributors (to this handbook).

So here is my issue: if assemblies are such an important feature for a 3D CAD software, how come none of you has tried to improve and otherwise to interact with existing assembly workbenches ? Before wanting to impose random grand visions on the rest of the FreeCAD community, I'd like to see proof that the people who write such things as :

> Assembly is a core feature of modern CAD systems

 do indeed know what assemblies are about, what are the specific problems and existing solutions. 

> Without an integrated assembly capability, users are **forced** to use one of several add-on options. With competing alternatives available, collaboration and interoperability is negatively affected

This is technical nonsense and only political propaganda. I know of course where this comes from, but before wanting to impose such obvious lies on the rest of us, I invite any wannabee contributor to be able to show complex assemblies that he had made using FreeCAD. Open-source is about "_show me the code_" so anyone pretending anything about assemblies will be invited to "_show me your assembly_" . 

There are many FreeCAD users who have indeed done assemblies, of various sizes and complexities, and who have posted their achievements in the forum, but they don't seem to have contributed to this "roadmap". Why is this roadmap not done in the open ? Why is this not discussed in the _Open Discussion_ forum ? What is the hidden agenda ?

**Comment by sliptonic** [comment]
Closing this issue since it lacks anything actionable.
