### ISSUE TITLE
Developers "Handbook" name is too similar to the FreeCAD Project Association "Handbook"

### ISSUE THREAD

**Issue by marcuspollio** [FreeCAD/DevelopersHandbook#94]
Hi there !

In order to reduce the potential for confusion, it would be sensible to adopt different terms for the documentation of the development side and the association side.
Although the use of the term "handbook" makes sense to a certain extent for both cases, a distinction is preferable.

A number of other closely related terms can be used :
For software development documentation, [Google](https://techdevguide.withgoogle.com/) uses "Tech Dev Guide", [WordPress](https://developer.wordpress.org/) uses "Developer Resources", [Apple](https://developer.apple.com/documentation/), [Blender](https://developer.blender.org/docs/) and [KiCAD](https://dev-docs.kicad.org/en/) uses simply "Developer Documentation" but also "Handbook" for Blender, etc. We can look into many other examples...
Some FOSS projects like [QGIS](https://qgis.org/en/site/getinvolved/development/) and [Inkscape](https://inkscape.org/develop/) do not have a special name for that but direct links to theirs Getting Started, Code Style, Repos, Debugging, etc.

For the Association side of things, most FOSS associations/foundations like the [Free Software Foundation](https://www.fsf.org/about/),  the [Open Source Initiative](https://opensource.org/about), [Blender](https://www.blender.org/about/foundation/) do not have any special name or a special "space" to describe precisely how they operate, but display some general information's on their main website, generally in the About page. Some like [Godot](https://godot.foundation/) have a dedicated website but no special name.

If you feel this issue is better posted in the FPA repo, I'll gladly do so =P
Thank you !

**Comment by obelisk79** [comment]
I wonder if disambiguation is necessary. A 'Handbook' is a type of document. Similar to the concept of a 'quick guide'. The Target, or purpose of which is delineated by the 'Developer' or 'FPA' aspect. Additionally it is also worth noting, that FPA is considered a separate (but related) organization.

From and online English dictionary:

> Handbook (noun):
> 
> 1a: a book capable of being conveniently carried as a ready reference : [manual](https://www.merriam-webster.com/dictionary/manual)
> b1: a concise reference book covering a particular subject

**Comment by chennes** [comment]
In these two cases "handbook" is more than just a descriptive term: it's an ethos for what we are striving for. See https://handbook.gitlab.com/handbook/company/culture/all-remote/handbook-first/

**Comment by obelisk79** [comment]
> In these two cases "handbook" is more than just a descriptive term: it's an ethos for what we are striving for. See https://handbook.gitlab.com/handbook/company/culture/all-remote/handbook-first/

That was an interesting read. Thanks for the link. While, I agree that a change is *not* necessary here, guidebook is a synonym for handbook according to Merriam-Webster, and thus should be an adequate alternative if deemed necessary without taking away from the spirit of the GitLab approach.

**Comment by yorikvanhavre** [comment]
Ultimately, I envison for the developer handbook to substitute the developer docs on the wiki, and become the official developers documentation. That might as well become its final name...

I guess with all the recent developments and efforts here and there, what constitutes our documentation is becoming a bit spread around different places and concepts... But probably at this point the important thing is that the content get written. The form can always much easier be fixed later on.

Also, this whole thing helps to migrate out of mediawiki, by already providing a good deal of docs as markdown...

**Comment by marcuspollio** [comment]
Thank you all three for your insights !

I appreciate the approach taken to documenting, writing down and organising the process. By the way, thank you sincerely for that, it is by far not the case in all projects, free software or not !

FreeCAD is growing, and so are its communities and infrastructure. More and more "organisms", sometimes with changing or interchangeable names, are evolving in this ecosystem. Personally, I feel it is better if consistent and unique names are given. That makes it easier to understand exactly what we are all talking about, especially for non-English speakers.

"Take a look at the handbook for how to update a maintainer's status... [Here](https://fpa.freecad.org/handbook/process/source_code_access.html), not [there](https://freecad.github.io/DevelopersHandbook/maintainersguide/)"

This also applies to the naming of other "administrative" aspects :
"donations" (one-time) / "sponsoring" (recurrent) / "funding" (external platforms)
"programs" / "initiatives"
"grants" (travel and the new grant program) / "development fund" / "jobs"
etc.

"FreeCAD has a new development grant program to support developers financially. It is one of the many initiatives the FreeCAD Project Association is funding thanks to the donations and sponsoring of its community."
Maybe it is clear enough, I do not know. No change is needed.

I'm not a proponent of change for change's sake. The initial question was rather that of the possible confusion between some of these names. If you do not think there i any risk, then I will close this issue.

**Comment by marcuspollio** [comment]
Hi @chennes and @yorikvanhavre !

Do you have any further comments? If not, I'll close this issue.

We can always re-evaluate names and clarify them if necessary later, when migration efforts are more advanced.

Thank you !
